[colors]
background = '#0f1416'
foreground = '#dee3e5'

cursor_bg = '#84d2e5'
cursor_fg = '#0f1416'
cursor_border = '#84d2e5'

selection_bg = '#004e5b'
selection_fg = '#dee3e5'

ansi = ['#0f1416', '#ff72a1', '#72e57e', '#fff572', '#6ac3d9', '#17596a', '#84d2e5', '#e2edf0']
brights = ['#899294', '#ff9fbf', '#a5ffae', '#fff9a5', '#a1eafb', '#b3f0ff', '#cef5ff', '#f8fdff']
